// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package eBankingServices.UserAccount;

public interface AccountInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAccount.AccountInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
