// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package eBankingServices.UserAccount;

public interface AccountInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAccount.AccountInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accNo = 1;</code>
   */
  int getAccNo();

  /**
   * <code>double amount = 2;</code>
   */
  double getAmount();

  /**
   * <code>double balance = 3;</code>
   */
  double getBalance();
}
