// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package eBankingServices.UserAccount;

public interface PasswordConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAccount.PasswordConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string passConf = 1;</code>
   */
  java.lang.String getPassConf();
  /**
   * <code>string passConf = 1;</code>
   */
  com.google.protobuf.ByteString
      getPassConfBytes();
}
