// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package eBankingServices.UserAccount;

public interface PasswordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAccount.PasswordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string currPass = 2;</code>
   */
  java.lang.String getCurrPass();
  /**
   * <code>string currPass = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrPassBytes();

  /**
   * <code>string newPass = 3;</code>
   */
  java.lang.String getNewPass();
  /**
   * <code>string newPass = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewPassBytes();
}
