// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package eBankingServices.UserAccount;

public interface ViewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserAccount.ViewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accNo = 1;</code>
   */
  int getAccNo();
}
