// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

/**
 * <pre>
 * interest calculator message
 * </pre>
 *
 * Protobuf type {@code UserTools.CalcRequest}
 */
public  final class CalcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserTools.CalcRequest)
    CalcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalcRequest.newBuilder() to construct.
  private CalcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalcRequest() {
    accType_ = "";
    sum_ = 0D;
    access_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accType_ = s;
            break;
          }
          case 17: {

            sum_ = input.readDouble();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            access_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_CalcRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_CalcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eBankingServices.UserTools.CalcRequest.class, eBankingServices.UserTools.CalcRequest.Builder.class);
  }

  public static final int ACCTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object accType_;
  /**
   * <code>string accType = 1;</code>
   */
  public java.lang.String getAccType() {
    java.lang.Object ref = accType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accType_ = s;
      return s;
    }
  }
  /**
   * <code>string accType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccTypeBytes() {
    java.lang.Object ref = accType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUM_FIELD_NUMBER = 2;
  private double sum_;
  /**
   * <code>double sum = 2;</code>
   */
  public double getSum() {
    return sum_;
  }

  public static final int ACCESS_FIELD_NUMBER = 3;
  private volatile java.lang.Object access_;
  /**
   * <code>string access = 3;</code>
   */
  public java.lang.String getAccess() {
    java.lang.Object ref = access_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      access_ = s;
      return s;
    }
  }
  /**
   * <code>string access = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAccessBytes() {
    java.lang.Object ref = access_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      access_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accType_);
    }
    if (sum_ != 0D) {
      output.writeDouble(2, sum_);
    }
    if (!getAccessBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, access_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accType_);
    }
    if (sum_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, sum_);
    }
    if (!getAccessBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, access_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eBankingServices.UserTools.CalcRequest)) {
      return super.equals(obj);
    }
    eBankingServices.UserTools.CalcRequest other = (eBankingServices.UserTools.CalcRequest) obj;

    boolean result = true;
    result = result && getAccType()
        .equals(other.getAccType());
    result = result && (
        java.lang.Double.doubleToLongBits(getSum())
        == java.lang.Double.doubleToLongBits(
            other.getSum()));
    result = result && getAccess()
        .equals(other.getAccess());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAccType().hashCode();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSum()));
    hash = (37 * hash) + ACCESS_FIELD_NUMBER;
    hash = (53 * hash) + getAccess().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eBankingServices.UserTools.CalcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.UserTools.CalcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.CalcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.CalcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eBankingServices.UserTools.CalcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * interest calculator message
   * </pre>
   *
   * Protobuf type {@code UserTools.CalcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserTools.CalcRequest)
      eBankingServices.UserTools.CalcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_CalcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_CalcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eBankingServices.UserTools.CalcRequest.class, eBankingServices.UserTools.CalcRequest.Builder.class);
    }

    // Construct using eBankingServices.UserTools.CalcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accType_ = "";

      sum_ = 0D;

      access_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_CalcRequest_descriptor;
    }

    @java.lang.Override
    public eBankingServices.UserTools.CalcRequest getDefaultInstanceForType() {
      return eBankingServices.UserTools.CalcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public eBankingServices.UserTools.CalcRequest build() {
      eBankingServices.UserTools.CalcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eBankingServices.UserTools.CalcRequest buildPartial() {
      eBankingServices.UserTools.CalcRequest result = new eBankingServices.UserTools.CalcRequest(this);
      result.accType_ = accType_;
      result.sum_ = sum_;
      result.access_ = access_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eBankingServices.UserTools.CalcRequest) {
        return mergeFrom((eBankingServices.UserTools.CalcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eBankingServices.UserTools.CalcRequest other) {
      if (other == eBankingServices.UserTools.CalcRequest.getDefaultInstance()) return this;
      if (!other.getAccType().isEmpty()) {
        accType_ = other.accType_;
        onChanged();
      }
      if (other.getSum() != 0D) {
        setSum(other.getSum());
      }
      if (!other.getAccess().isEmpty()) {
        access_ = other.access_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eBankingServices.UserTools.CalcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eBankingServices.UserTools.CalcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accType_ = "";
    /**
     * <code>string accType = 1;</code>
     */
    public java.lang.String getAccType() {
      java.lang.Object ref = accType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccTypeBytes() {
      java.lang.Object ref = accType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accType = 1;</code>
     */
    public Builder setAccType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accType = 1;</code>
     */
    public Builder clearAccType() {
      
      accType_ = getDefaultInstance().getAccType();
      onChanged();
      return this;
    }
    /**
     * <code>string accType = 1;</code>
     */
    public Builder setAccTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accType_ = value;
      onChanged();
      return this;
    }

    private double sum_ ;
    /**
     * <code>double sum = 2;</code>
     */
    public double getSum() {
      return sum_;
    }
    /**
     * <code>double sum = 2;</code>
     */
    public Builder setSum(double value) {
      
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double sum = 2;</code>
     */
    public Builder clearSum() {
      
      sum_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object access_ = "";
    /**
     * <code>string access = 3;</code>
     */
    public java.lang.String getAccess() {
      java.lang.Object ref = access_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        access_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string access = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccessBytes() {
      java.lang.Object ref = access_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        access_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string access = 3;</code>
     */
    public Builder setAccess(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      access_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string access = 3;</code>
     */
    public Builder clearAccess() {
      
      access_ = getDefaultInstance().getAccess();
      onChanged();
      return this;
    }
    /**
     * <code>string access = 3;</code>
     */
    public Builder setAccessBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      access_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserTools.CalcRequest)
  }

  // @@protoc_insertion_point(class_scope:UserTools.CalcRequest)
  private static final eBankingServices.UserTools.CalcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eBankingServices.UserTools.CalcRequest();
  }

  public static eBankingServices.UserTools.CalcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalcRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalcRequest>() {
    @java.lang.Override
    public CalcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eBankingServices.UserTools.CalcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

