// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface CalcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.CalcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accType = 1;</code>
   */
  java.lang.String getAccType();
  /**
   * <code>string accType = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccTypeBytes();

  /**
   * <code>double sum = 2;</code>
   */
  double getSum();

  /**
   * <code>string access = 3;</code>
   */
  java.lang.String getAccess();
  /**
   * <code>string access = 3;</code>
   */
  com.google.protobuf.ByteString
      getAccessBytes();
}
