// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface CalcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.CalcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   */
  int getSum();

  /**
   * <code>int32 interestRate = 2;</code>
   */
  int getInterestRate();
}
