// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface CalcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.CalcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double interest = 1;</code>
   */
  double getInterest();

  /**
   * <code>string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
