// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface HelpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.HelpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 problemID = 1;</code>
   */
  int getProblemID();

  /**
   * <code>.UserTools.HelpRequest.Solutions solutions = 2;</code>
   */
  int getSolutionsValue();
  /**
   * <code>.UserTools.HelpRequest.Solutions solutions = 2;</code>
   */
  eBankingServices.UserTools.HelpRequest.Solutions getSolutions();
}
