// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface HelpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.HelpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string solution = 1;</code>
   */
  java.lang.String getSolution();
  /**
   * <code>string solution = 1;</code>
   */
  com.google.protobuf.ByteString
      getSolutionBytes();
}
