// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface HelpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.HelpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UserTools.HelpRequest.Operation operation = 1;</code>
   */
  int getOperationValue();
  /**
   * <code>.UserTools.HelpRequest.Operation operation = 1;</code>
   */
  eBankingServices.UserTools.HelpRequest.Operation getOperation();
}
