// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public final class UserToolsImpl {
  private UserToolsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_VaultAccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_VaultAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_VaultConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_VaultConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserTools.proto\022\tUserTools\"\236\001\n\013HelpReq" +
      "uest\022\017\n\007message\030\001 \001(\t\0223\n\toperation\030\002 \001(\016" +
      "2 .UserTools.HelpRequest.Operation\"I\n\tOp" +
      "eration\022\022\n\016PASSWORD_RESET\020\000\022\016\n\nREPORT_BU" +
      "G\020\001\022\n\n\006VAULTS\020\002\022\014\n\010PAYMENTS\020\003\"2\n\014HelpRes" +
      "ponse\022\020\n\010problems\030\001 \001(\t\022\020\n\010solution\030\002 \001(" +
      "\t\"r\n\013VaultAccess\022\r\n\005accNo\030\001 \001(\005\022\013\n\003sum\030\002" +
      " \001(\001\022\022\n\nunlockDate\030\003 \001(\t\022\017\n\007vaultID\030\004 \001(" +
      "\005\022\020\n\010username\030\005 \001(\t\022\020\n\010password\030\006 \001(\t\"&\n" +
      "\021VaultConfirmation\022\021\n\tvaultConf\030\003 \001(\t\";\n" +
      "\013CalcRequest\022\017\n\007accType\030\001 \001(\t\022\013\n\003sum\030\002 \001" +
      "(\001\022\016\n\006access\030\003 \001(\t\"\037\n\014CalcResponse\022\017\n\007me" +
      "ssage\030\001 \001(\t2\323\001\n\tUserTools\022@\n\007HelpBot\022\026.U" +
      "serTools.HelpRequest\032\027.UserTools.HelpRes" +
      "ponse\"\000(\0010\001\022?\n\005Vault\022\026.UserTools.VaultAc" +
      "cess\032\034.UserTools.VaultConfirmation\"\000\022C\n\014" +
      "InterestCalc\022\026.UserTools.CalcRequest\032\027.U" +
      "serTools.CalcResponse\"\000(\001B-\n\032eBankingSer" +
      "vices.UserToolsB\rUserToolsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserTools_HelpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserTools_HelpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpRequest_descriptor,
        new java.lang.String[] { "Message", "Operation", });
    internal_static_UserTools_HelpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserTools_HelpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpResponse_descriptor,
        new java.lang.String[] { "Problems", "Solution", });
    internal_static_UserTools_VaultAccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserTools_VaultAccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_VaultAccess_descriptor,
        new java.lang.String[] { "AccNo", "Sum", "UnlockDate", "VaultID", "Username", "Password", });
    internal_static_UserTools_VaultConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserTools_VaultConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_VaultConfirmation_descriptor,
        new java.lang.String[] { "VaultConf", });
    internal_static_UserTools_CalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserTools_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcRequest_descriptor,
        new java.lang.String[] { "AccType", "Sum", "Access", });
    internal_static_UserTools_CalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UserTools_CalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
