// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public final class UserToolsImpl {
  private UserToolsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_VaultAccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_VaultAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_VaultConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_VaultConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserTools.proto\022\tUserTools\"\240\001\n\013HelpReq" +
      "uest\022\021\n\tproblemID\030\001 \001(\005\0223\n\tsolutions\030\002 \001" +
      "(\0162 .UserTools.HelpRequest.Solutions\"I\n\t" +
      "Solutions\022\022\n\016PASSWORD_RESET\020\000\022\016\n\nREPORT_" +
      "BUG\020\001\022\n\n\006VAULTS\020\002\022\014\n\010PAYMENTS\020\003\" \n\014HelpR" +
      "esponse\022\020\n\010solution\030\001 \001(\t\"r\n\013VaultAccess" +
      "\022\r\n\005accNo\030\001 \001(\005\022\013\n\003sum\030\002 \001(\005\022\022\n\nunlockDa" +
      "te\030\003 \001(\t\022\017\n\007vaultID\030\004 \001(\005\022\020\n\010username\030\005 " +
      "\001(\t\022\020\n\010password\030\006 \001(\t\"&\n\021VaultConfirmati" +
      "on\022\021\n\tvaultConf\030\003 \001(\t\"0\n\013CalcRequest\022\013\n\003" +
      "sum\030\001 \001(\005\022\024\n\014interestRate\030\002 \001(\005\"\035\n\014CalcR" +
      "esponse\022\r\n\005total\030\001 \001(\0052\323\001\n\tUserTools\022@\n\007" +
      "HelpBot\022\026.UserTools.HelpRequest\032\027.UserTo" +
      "ols.HelpResponse\"\000(\0010\001\022?\n\005Vault\022\026.UserTo" +
      "ols.VaultAccess\032\034.UserTools.VaultConfirm" +
      "ation\"\000\022C\n\014InterestCalc\022\026.UserTools.Calc" +
      "Request\032\027.UserTools.CalcResponse\"\000(\001B-\n\032" +
      "eBankingServices.UserToolsB\rUserToolsImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserTools_HelpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserTools_HelpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpRequest_descriptor,
        new java.lang.String[] { "ProblemID", "Solutions", });
    internal_static_UserTools_HelpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserTools_HelpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpResponse_descriptor,
        new java.lang.String[] { "Solution", });
    internal_static_UserTools_VaultAccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserTools_VaultAccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_VaultAccess_descriptor,
        new java.lang.String[] { "AccNo", "Sum", "UnlockDate", "VaultID", "Username", "Password", });
    internal_static_UserTools_VaultConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserTools_VaultConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_VaultConfirmation_descriptor,
        new java.lang.String[] { "VaultConf", });
    internal_static_UserTools_CalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserTools_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcRequest_descriptor,
        new java.lang.String[] { "Sum", "InterestRate", });
    internal_static_UserTools_CalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UserTools_CalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcResponse_descriptor,
        new java.lang.String[] { "Total", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
