// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public final class UserToolsImpl {
  private UserToolsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_HelpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_HelpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_ValutAccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_ValutAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_VaultConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_VaultConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTools_CalcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTools_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserTools.proto\022\tUserTools\" \n\013HelpRequ" +
      "est\022\021\n\tproblemID\030\001 \001(\005\" \n\014HelpResponse\022\020" +
      "\n\010solution\030\001 \001(\t\"=\n\013ValutAccess\022\r\n\005accNo" +
      "\030\001 \001(\t\022\013\n\003sum\030\002 \001(\t\022\022\n\nunlockDate\030\003 \001(\t\"" +
      "7\n\021VaultConfirmation\022\017\n\007vaultID\030\001 \001(\005\022\021\n" +
      "\tvalutConf\030\002 \001(\t\"0\n\013CalcRequest\022\013\n\003sum\030\001" +
      " \001(\005\022\024\n\014interestRate\030\002 \001(\005\"\035\n\014CalcRespon" +
      "se\022\r\n\005total\030\001 \001(\0052\321\001\n\tUserTools\022>\n\007HelpB" +
      "ot\022\026.UserTools.HelpRequest\032\027.UserTools.H" +
      "elpResponse\"\000(\001\022?\n\005Vault\022\026.UserTools.Val" +
      "utAccess\032\034.UserTools.VaultConfirmation\"\000" +
      "\022C\n\014InterestCalc\022\026.UserTools.CalcRequest" +
      "\032\027.UserTools.CalcResponse\"\000(\001B-\n\032eBankin" +
      "gServices.UserToolsB\rUserToolsImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserTools_HelpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserTools_HelpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpRequest_descriptor,
        new java.lang.String[] { "ProblemID", });
    internal_static_UserTools_HelpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserTools_HelpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_HelpResponse_descriptor,
        new java.lang.String[] { "Solution", });
    internal_static_UserTools_ValutAccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserTools_ValutAccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_ValutAccess_descriptor,
        new java.lang.String[] { "AccNo", "Sum", "UnlockDate", });
    internal_static_UserTools_VaultConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserTools_VaultConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_VaultConfirmation_descriptor,
        new java.lang.String[] { "VaultID", "ValutConf", });
    internal_static_UserTools_CalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserTools_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcRequest_descriptor,
        new java.lang.String[] { "Sum", "InterestRate", });
    internal_static_UserTools_CalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UserTools_CalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTools_CalcResponse_descriptor,
        new java.lang.String[] { "Total", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
