// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

/**
 * <pre>
 * valut message
 * </pre>
 *
 * Protobuf type {@code UserTools.ValutAccess}
 */
public  final class ValutAccess extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserTools.ValutAccess)
    ValutAccessOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValutAccess.newBuilder() to construct.
  private ValutAccess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValutAccess() {
    accNo_ = "";
    sum_ = "";
    unlockDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValutAccess(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accNo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sum_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            unlockDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_ValutAccess_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_ValutAccess_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eBankingServices.UserTools.ValutAccess.class, eBankingServices.UserTools.ValutAccess.Builder.class);
  }

  public static final int ACCNO_FIELD_NUMBER = 1;
  private volatile java.lang.Object accNo_;
  /**
   * <code>string accNo = 1;</code>
   */
  public java.lang.String getAccNo() {
    java.lang.Object ref = accNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accNo_ = s;
      return s;
    }
  }
  /**
   * <code>string accNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccNoBytes() {
    java.lang.Object ref = accNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUM_FIELD_NUMBER = 2;
  private volatile java.lang.Object sum_;
  /**
   * <code>string sum = 2;</code>
   */
  public java.lang.String getSum() {
    java.lang.Object ref = sum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sum_ = s;
      return s;
    }
  }
  /**
   * <code>string sum = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSumBytes() {
    java.lang.Object ref = sum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNLOCKDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object unlockDate_;
  /**
   * <code>string unlockDate = 3;</code>
   */
  public java.lang.String getUnlockDate() {
    java.lang.Object ref = unlockDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unlockDate_ = s;
      return s;
    }
  }
  /**
   * <code>string unlockDate = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUnlockDateBytes() {
    java.lang.Object ref = unlockDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unlockDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accNo_);
    }
    if (!getSumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sum_);
    }
    if (!getUnlockDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unlockDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accNo_);
    }
    if (!getSumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sum_);
    }
    if (!getUnlockDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unlockDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eBankingServices.UserTools.ValutAccess)) {
      return super.equals(obj);
    }
    eBankingServices.UserTools.ValutAccess other = (eBankingServices.UserTools.ValutAccess) obj;

    boolean result = true;
    result = result && getAccNo()
        .equals(other.getAccNo());
    result = result && getSum()
        .equals(other.getSum());
    result = result && getUnlockDate()
        .equals(other.getUnlockDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCNO_FIELD_NUMBER;
    hash = (53 * hash) + getAccNo().hashCode();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + getSum().hashCode();
    hash = (37 * hash) + UNLOCKDATE_FIELD_NUMBER;
    hash = (53 * hash) + getUnlockDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eBankingServices.UserTools.ValutAccess parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.UserTools.ValutAccess parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.ValutAccess parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.UserTools.ValutAccess parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eBankingServices.UserTools.ValutAccess prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * valut message
   * </pre>
   *
   * Protobuf type {@code UserTools.ValutAccess}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserTools.ValutAccess)
      eBankingServices.UserTools.ValutAccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_ValutAccess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_ValutAccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eBankingServices.UserTools.ValutAccess.class, eBankingServices.UserTools.ValutAccess.Builder.class);
    }

    // Construct using eBankingServices.UserTools.ValutAccess.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accNo_ = "";

      sum_ = "";

      unlockDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eBankingServices.UserTools.UserToolsImpl.internal_static_UserTools_ValutAccess_descriptor;
    }

    @java.lang.Override
    public eBankingServices.UserTools.ValutAccess getDefaultInstanceForType() {
      return eBankingServices.UserTools.ValutAccess.getDefaultInstance();
    }

    @java.lang.Override
    public eBankingServices.UserTools.ValutAccess build() {
      eBankingServices.UserTools.ValutAccess result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eBankingServices.UserTools.ValutAccess buildPartial() {
      eBankingServices.UserTools.ValutAccess result = new eBankingServices.UserTools.ValutAccess(this);
      result.accNo_ = accNo_;
      result.sum_ = sum_;
      result.unlockDate_ = unlockDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eBankingServices.UserTools.ValutAccess) {
        return mergeFrom((eBankingServices.UserTools.ValutAccess)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eBankingServices.UserTools.ValutAccess other) {
      if (other == eBankingServices.UserTools.ValutAccess.getDefaultInstance()) return this;
      if (!other.getAccNo().isEmpty()) {
        accNo_ = other.accNo_;
        onChanged();
      }
      if (!other.getSum().isEmpty()) {
        sum_ = other.sum_;
        onChanged();
      }
      if (!other.getUnlockDate().isEmpty()) {
        unlockDate_ = other.unlockDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eBankingServices.UserTools.ValutAccess parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eBankingServices.UserTools.ValutAccess) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accNo_ = "";
    /**
     * <code>string accNo = 1;</code>
     */
    public java.lang.String getAccNo() {
      java.lang.Object ref = accNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccNoBytes() {
      java.lang.Object ref = accNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accNo = 1;</code>
     */
    public Builder setAccNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accNo = 1;</code>
     */
    public Builder clearAccNo() {
      
      accNo_ = getDefaultInstance().getAccNo();
      onChanged();
      return this;
    }
    /**
     * <code>string accNo = 1;</code>
     */
    public Builder setAccNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sum_ = "";
    /**
     * <code>string sum = 2;</code>
     */
    public java.lang.String getSum() {
      java.lang.Object ref = sum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sum = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSumBytes() {
      java.lang.Object ref = sum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sum = 2;</code>
     */
    public Builder setSum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sum = 2;</code>
     */
    public Builder clearSum() {
      
      sum_ = getDefaultInstance().getSum();
      onChanged();
      return this;
    }
    /**
     * <code>string sum = 2;</code>
     */
    public Builder setSumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sum_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object unlockDate_ = "";
    /**
     * <code>string unlockDate = 3;</code>
     */
    public java.lang.String getUnlockDate() {
      java.lang.Object ref = unlockDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unlockDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string unlockDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnlockDateBytes() {
      java.lang.Object ref = unlockDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unlockDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string unlockDate = 3;</code>
     */
    public Builder setUnlockDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unlockDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string unlockDate = 3;</code>
     */
    public Builder clearUnlockDate() {
      
      unlockDate_ = getDefaultInstance().getUnlockDate();
      onChanged();
      return this;
    }
    /**
     * <code>string unlockDate = 3;</code>
     */
    public Builder setUnlockDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unlockDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserTools.ValutAccess)
  }

  // @@protoc_insertion_point(class_scope:UserTools.ValutAccess)
  private static final eBankingServices.UserTools.ValutAccess DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eBankingServices.UserTools.ValutAccess();
  }

  public static eBankingServices.UserTools.ValutAccess getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValutAccess>
      PARSER = new com.google.protobuf.AbstractParser<ValutAccess>() {
    @java.lang.Override
    public ValutAccess parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValutAccess(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValutAccess> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValutAccess> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eBankingServices.UserTools.ValutAccess getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

