// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface VaultConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.VaultConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 vaultID = 1;</code>
   */
  int getVaultID();

  /**
   * <code>string vaultConf = 2;</code>
   */
  java.lang.String getVaultConf();
  /**
   * <code>string vaultConf = 2;</code>
   */
  com.google.protobuf.ByteString
      getVaultConfBytes();
}
