// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface VaultAccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.VaultAccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accNo = 1;</code>
   */
  int getAccNo();

  /**
   * <code>int32 sum = 2;</code>
   */
  int getSum();

  /**
   * <code>string unlockDate = 3;</code>
   */
  java.lang.String getUnlockDate();
  /**
   * <code>string unlockDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getUnlockDateBytes();

  /**
   * <code>int32 vaultID = 4;</code>
   */
  int getVaultID();

  /**
   * <code>string username = 5;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 5;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 6;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 6;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
