// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTools.proto

package eBankingServices.UserTools;

public interface VaultAccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserTools.VaultAccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accNo = 1;</code>
   */
  java.lang.String getAccNo();
  /**
   * <code>string accNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccNoBytes();

  /**
   * <code>string sum = 2;</code>
   */
  java.lang.String getSum();
  /**
   * <code>string sum = 2;</code>
   */
  com.google.protobuf.ByteString
      getSumBytes();

  /**
   * <code>string unlockDate = 3;</code>
   */
  java.lang.String getUnlockDate();
  /**
   * <code>string unlockDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getUnlockDateBytes();
}
