// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface DepositConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.DepositConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 depositID = 1;</code>
   */
  int getDepositID();

  /**
   * <code>string depositConf = 2;</code>
   */
  java.lang.String getDepositConf();
  /**
   * <code>string depositConf = 2;</code>
   */
  com.google.protobuf.ByteString
      getDepositConfBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
