// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface DepositSumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.DepositSum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accNo = 1;</code>
   */
  java.lang.String getAccNo();
  /**
   * <code>string accNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccNoBytes();

  /**
   * <code>string sum = 2;</code>
   */
  java.lang.String getSum();
  /**
   * <code>string sum = 2;</code>
   */
  com.google.protobuf.ByteString
      getSumBytes();
}
