// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface DepositSumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.DepositSum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accNo = 1;</code>
   */
  int getAccNo();

  /**
   * <code>double sum = 2;</code>
   */
  double getSum();
}
