// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

/**
 * <pre>
 * request message
 * </pre>
 *
 * Protobuf type {@code Transactions.RequestSum}
 */
public  final class RequestSum extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Transactions.RequestSum)
    RequestSumOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestSum.newBuilder() to construct.
  private RequestSum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestSum() {
    fromAccNo_ = "";
    toAccNo_ = "";
    sum_ = "";
    monthly_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestSum(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fromAccNo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            toAccNo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sum_ = s;
            break;
          }
          case 32: {

            monthly_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_RequestSum_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_RequestSum_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eBankingServices.Transactions.RequestSum.class, eBankingServices.Transactions.RequestSum.Builder.class);
  }

  public static final int FROM_ACCNO_FIELD_NUMBER = 1;
  private volatile java.lang.Object fromAccNo_;
  /**
   * <code>string from_accNo = 1;</code>
   */
  public java.lang.String getFromAccNo() {
    java.lang.Object ref = fromAccNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromAccNo_ = s;
      return s;
    }
  }
  /**
   * <code>string from_accNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFromAccNoBytes() {
    java.lang.Object ref = fromAccNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromAccNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_ACCNO_FIELD_NUMBER = 2;
  private volatile java.lang.Object toAccNo_;
  /**
   * <code>string to_accNo = 2;</code>
   */
  public java.lang.String getToAccNo() {
    java.lang.Object ref = toAccNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toAccNo_ = s;
      return s;
    }
  }
  /**
   * <code>string to_accNo = 2;</code>
   */
  public com.google.protobuf.ByteString
      getToAccNoBytes() {
    java.lang.Object ref = toAccNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toAccNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUM_FIELD_NUMBER = 3;
  private volatile java.lang.Object sum_;
  /**
   * <code>string sum = 3;</code>
   */
  public java.lang.String getSum() {
    java.lang.Object ref = sum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sum_ = s;
      return s;
    }
  }
  /**
   * <code>string sum = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSumBytes() {
    java.lang.Object ref = sum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MONTHLY_FIELD_NUMBER = 4;
  private boolean monthly_;
  /**
   * <code>bool monthly = 4;</code>
   */
  public boolean getMonthly() {
    return monthly_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFromAccNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromAccNo_);
    }
    if (!getToAccNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toAccNo_);
    }
    if (!getSumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sum_);
    }
    if (monthly_ != false) {
      output.writeBool(4, monthly_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFromAccNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromAccNo_);
    }
    if (!getToAccNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toAccNo_);
    }
    if (!getSumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sum_);
    }
    if (monthly_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, monthly_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eBankingServices.Transactions.RequestSum)) {
      return super.equals(obj);
    }
    eBankingServices.Transactions.RequestSum other = (eBankingServices.Transactions.RequestSum) obj;

    boolean result = true;
    result = result && getFromAccNo()
        .equals(other.getFromAccNo());
    result = result && getToAccNo()
        .equals(other.getToAccNo());
    result = result && getSum()
        .equals(other.getSum());
    result = result && (getMonthly()
        == other.getMonthly());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_ACCNO_FIELD_NUMBER;
    hash = (53 * hash) + getFromAccNo().hashCode();
    hash = (37 * hash) + TO_ACCNO_FIELD_NUMBER;
    hash = (53 * hash) + getToAccNo().hashCode();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + getSum().hashCode();
    hash = (37 * hash) + MONTHLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMonthly());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eBankingServices.Transactions.RequestSum parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.Transactions.RequestSum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.RequestSum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.RequestSum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eBankingServices.Transactions.RequestSum prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * request message
   * </pre>
   *
   * Protobuf type {@code Transactions.RequestSum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Transactions.RequestSum)
      eBankingServices.Transactions.RequestSumOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_RequestSum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_RequestSum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eBankingServices.Transactions.RequestSum.class, eBankingServices.Transactions.RequestSum.Builder.class);
    }

    // Construct using eBankingServices.Transactions.RequestSum.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fromAccNo_ = "";

      toAccNo_ = "";

      sum_ = "";

      monthly_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_RequestSum_descriptor;
    }

    @java.lang.Override
    public eBankingServices.Transactions.RequestSum getDefaultInstanceForType() {
      return eBankingServices.Transactions.RequestSum.getDefaultInstance();
    }

    @java.lang.Override
    public eBankingServices.Transactions.RequestSum build() {
      eBankingServices.Transactions.RequestSum result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eBankingServices.Transactions.RequestSum buildPartial() {
      eBankingServices.Transactions.RequestSum result = new eBankingServices.Transactions.RequestSum(this);
      result.fromAccNo_ = fromAccNo_;
      result.toAccNo_ = toAccNo_;
      result.sum_ = sum_;
      result.monthly_ = monthly_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eBankingServices.Transactions.RequestSum) {
        return mergeFrom((eBankingServices.Transactions.RequestSum)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eBankingServices.Transactions.RequestSum other) {
      if (other == eBankingServices.Transactions.RequestSum.getDefaultInstance()) return this;
      if (!other.getFromAccNo().isEmpty()) {
        fromAccNo_ = other.fromAccNo_;
        onChanged();
      }
      if (!other.getToAccNo().isEmpty()) {
        toAccNo_ = other.toAccNo_;
        onChanged();
      }
      if (!other.getSum().isEmpty()) {
        sum_ = other.sum_;
        onChanged();
      }
      if (other.getMonthly() != false) {
        setMonthly(other.getMonthly());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eBankingServices.Transactions.RequestSum parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eBankingServices.Transactions.RequestSum) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fromAccNo_ = "";
    /**
     * <code>string from_accNo = 1;</code>
     */
    public java.lang.String getFromAccNo() {
      java.lang.Object ref = fromAccNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAccNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from_accNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromAccNoBytes() {
      java.lang.Object ref = fromAccNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from_accNo = 1;</code>
     */
    public Builder setFromAccNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromAccNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from_accNo = 1;</code>
     */
    public Builder clearFromAccNo() {
      
      fromAccNo_ = getDefaultInstance().getFromAccNo();
      onChanged();
      return this;
    }
    /**
     * <code>string from_accNo = 1;</code>
     */
    public Builder setFromAccNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromAccNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toAccNo_ = "";
    /**
     * <code>string to_accNo = 2;</code>
     */
    public java.lang.String getToAccNo() {
      java.lang.Object ref = toAccNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAccNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string to_accNo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToAccNoBytes() {
      java.lang.Object ref = toAccNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to_accNo = 2;</code>
     */
    public Builder setToAccNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toAccNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to_accNo = 2;</code>
     */
    public Builder clearToAccNo() {
      
      toAccNo_ = getDefaultInstance().getToAccNo();
      onChanged();
      return this;
    }
    /**
     * <code>string to_accNo = 2;</code>
     */
    public Builder setToAccNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toAccNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sum_ = "";
    /**
     * <code>string sum = 3;</code>
     */
    public java.lang.String getSum() {
      java.lang.Object ref = sum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sum = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSumBytes() {
      java.lang.Object ref = sum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sum = 3;</code>
     */
    public Builder setSum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sum = 3;</code>
     */
    public Builder clearSum() {
      
      sum_ = getDefaultInstance().getSum();
      onChanged();
      return this;
    }
    /**
     * <code>string sum = 3;</code>
     */
    public Builder setSumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sum_ = value;
      onChanged();
      return this;
    }

    private boolean monthly_ ;
    /**
     * <code>bool monthly = 4;</code>
     */
    public boolean getMonthly() {
      return monthly_;
    }
    /**
     * <code>bool monthly = 4;</code>
     */
    public Builder setMonthly(boolean value) {
      
      monthly_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool monthly = 4;</code>
     */
    public Builder clearMonthly() {
      
      monthly_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Transactions.RequestSum)
  }

  // @@protoc_insertion_point(class_scope:Transactions.RequestSum)
  private static final eBankingServices.Transactions.RequestSum DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eBankingServices.Transactions.RequestSum();
  }

  public static eBankingServices.Transactions.RequestSum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestSum>
      PARSER = new com.google.protobuf.AbstractParser<RequestSum>() {
    @java.lang.Override
    public RequestSum parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestSum(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestSum> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestSum> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eBankingServices.Transactions.RequestSum getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

