// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface RequestStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.RequestStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestID = 1;</code>
   */
  int getRequestID();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string requestConf = 3;</code>
   */
  java.lang.String getRequestConf();
  /**
   * <code>string requestConf = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequestConfBytes();
}
