// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface RequestSumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.RequestSum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_accNo = 1;</code>
   */
  java.lang.String getFromAccNo();
  /**
   * <code>string from_accNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromAccNoBytes();

  /**
   * <code>string to_accNo = 2;</code>
   */
  java.lang.String getToAccNo();
  /**
   * <code>string to_accNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getToAccNoBytes();

  /**
   * <code>string sum = 3;</code>
   */
  java.lang.String getSum();
  /**
   * <code>string sum = 3;</code>
   */
  com.google.protobuf.ByteString
      getSumBytes();

  /**
   * <code>bool monthly = 4;</code>
   */
  boolean getMonthly();
}
