// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface TransferConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.TransferConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 transferID = 1;</code>
   */
  int getTransferID();

  /**
   * <code>string transferConf = 2;</code>
   */
  java.lang.String getTransferConf();
  /**
   * <code>string transferConf = 2;</code>
   */
  com.google.protobuf.ByteString
      getTransferConfBytes();
}
