// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

import io.grpc.ManagedChannelBuilder;

/**
 * Protobuf type {@code Transactions.TransferConfirmation}
 */
public  final class TransferConfirmation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Transactions.TransferConfirmation)
    TransferConfirmationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransferConfirmation.newBuilder() to construct.
  private TransferConfirmation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransferConfirmation() {
    transferID_ = 0;
    transferConf_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransferConfirmation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            transferID_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            transferConf_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_TransferConfirmation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_TransferConfirmation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eBankingServices.Transactions.TransferConfirmation.class, eBankingServices.Transactions.TransferConfirmation.Builder.class);
  }

  public static final int TRANSFERID_FIELD_NUMBER = 1;
  private int transferID_;
  /**
   * <code>int32 transferID = 1;</code>
   */
  public int getTransferID() {
    return transferID_;
  }

  public static final int TRANSFERCONF_FIELD_NUMBER = 2;
  private volatile java.lang.Object transferConf_;
  /**
   * <code>string transferConf = 2;</code>
   */
  public java.lang.String getTransferConf() {
    java.lang.Object ref = transferConf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transferConf_ = s;
      return s;
    }
  }
  /**
   * <code>string transferConf = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTransferConfBytes() {
    java.lang.Object ref = transferConf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transferConf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transferID_ != 0) {
      output.writeInt32(1, transferID_);
    }
    if (!getTransferConfBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transferConf_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transferID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, transferID_);
    }
    if (!getTransferConfBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transferConf_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eBankingServices.Transactions.TransferConfirmation)) {
      return super.equals(obj);
    }
    eBankingServices.Transactions.TransferConfirmation other = (eBankingServices.Transactions.TransferConfirmation) obj;

    boolean result = true;
    result = result && (getTransferID()
        == other.getTransferID());
    result = result && getTransferConf()
        .equals(other.getTransferConf());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSFERID_FIELD_NUMBER;
    hash = (53 * hash) + getTransferID();
    hash = (37 * hash) + TRANSFERCONF_FIELD_NUMBER;
    hash = (53 * hash) + getTransferConf().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eBankingServices.Transactions.TransferConfirmation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eBankingServices.Transactions.TransferConfirmation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Transactions.TransferConfirmation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Transactions.TransferConfirmation)
      eBankingServices.Transactions.TransferConfirmationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_TransferConfirmation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_TransferConfirmation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eBankingServices.Transactions.TransferConfirmation.class, eBankingServices.Transactions.TransferConfirmation.Builder.class);
    }

    // Construct using eBankingServices.Transactions.TransferConfirmation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      transferID_ = 0;

      transferConf_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eBankingServices.Transactions.TransactionsImpl.internal_static_Transactions_TransferConfirmation_descriptor;
    }

    @java.lang.Override
    public eBankingServices.Transactions.TransferConfirmation getDefaultInstanceForType() {
      return eBankingServices.Transactions.TransferConfirmation.getDefaultInstance();
    }

    @java.lang.Override
    public eBankingServices.Transactions.TransferConfirmation build() {
      eBankingServices.Transactions.TransferConfirmation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eBankingServices.Transactions.TransferConfirmation buildPartial() {
      eBankingServices.Transactions.TransferConfirmation result = new eBankingServices.Transactions.TransferConfirmation(this);
      result.transferID_ = transferID_;
      result.transferConf_ = transferConf_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eBankingServices.Transactions.TransferConfirmation) {
        return mergeFrom((eBankingServices.Transactions.TransferConfirmation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eBankingServices.Transactions.TransferConfirmation other) {
      if (other == eBankingServices.Transactions.TransferConfirmation.getDefaultInstance()) return this;
      if (other.getTransferID() != 0) {
        setTransferID(other.getTransferID());
      }
      if (!other.getTransferConf().isEmpty()) {
        transferConf_ = other.transferConf_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eBankingServices.Transactions.TransferConfirmation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eBankingServices.Transactions.TransferConfirmation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int transferID_ ;
    /**
     * <code>int32 transferID = 1;</code>
     */
    public int getTransferID() {
      return transferID_;
    }
    /**
     * <code>int32 transferID = 1;</code>
     */
    public Builder setTransferID(int value) {
      
      transferID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transferID = 1;</code>
     */
    public Builder clearTransferID() {
      
      transferID_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object transferConf_ = "";
    /**
     * <code>string transferConf = 2;</code>
     */
    public java.lang.String getTransferConf() {
      java.lang.Object ref = transferConf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transferConf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transferConf = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransferConfBytes() {
      java.lang.Object ref = transferConf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transferConf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transferConf = 2;</code>
     */
    public Builder setTransferConf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transferConf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transferConf = 2;</code>
     */
    public Builder clearTransferConf() {
      
      transferConf_ = getDefaultInstance().getTransferConf();
      onChanged();
      return this;
    }
    /**
     * <code>string transferConf = 2;</code>
     */
    public Builder setTransferConfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transferConf_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

	public ManagedChannelBuilder setMessage(String string) {
		// TODO Auto-generated method stub
		return null;
	}

    // @@protoc_insertion_point(builder_scope:Transactions.TransferConfirmation)
  }

  // @@protoc_insertion_point(class_scope:Transactions.TransferConfirmation)
  private static final eBankingServices.Transactions.TransferConfirmation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eBankingServices.Transactions.TransferConfirmation();
  }

  public static eBankingServices.Transactions.TransferConfirmation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransferConfirmation>
      PARSER = new com.google.protobuf.AbstractParser<TransferConfirmation>() {
    @java.lang.Override
    public TransferConfirmation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransferConfirmation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransferConfirmation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransferConfirmation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eBankingServices.Transactions.TransferConfirmation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

