// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface TransferConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.TransferConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conf = 1;</code>
   */
  java.lang.String getConf();
  /**
   * <code>string conf = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfBytes();
}
