// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transactions.proto

package eBankingServices.Transactions;

public interface TransferSumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transactions.TransferSum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from_accNo = 1;</code>
   */
  int getFromAccNo();

  /**
   * <code>int32 to_accNo = 2;</code>
   */
  int getToAccNo();

  /**
   * <code>double sum = 3;</code>
   */
  double getSum();

  /**
   * <code>string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
